Repository seriouslysean/monster-hunter-now-events, pull requests merged in 2023-10, with the labels that each got.

#12 Add support for repeat events, resolves #1
  dist/events.ics
  package-lock.json
  package.json
  src/generate-events-ics.js
  src/utils/chat-gpt.js
Labels: enhancement

#15 Create issue templates, resolves #14
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/QUESTION.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#23 ci: create pre-commit.yml
  .github/workflows/pre-commit.yml
Labels: enhancement, hacktoberfest

#24 Update documentation with more information
  docs/README.md
  events.json
Labels: documentation

#27 Feature/rollbar
  .env.example
  package-lock.json
  package.json
  src/utils/chat-gpt.js
  src/utils/config.js
  src/utils/log-utils.js
  tools/test-logger.js
Labels: enhancement, hacktoberfest

#29 Prevent deduping if events.json file is up to date
  dist/events.ics
  dist/events.json
  package-lock.json
  package.json
  src/generate-events-ics.js
  src/generate-events-json.js
  src/utils/chat-gpt.js
  src/utils/utils.js
Labels: bug, hacktoberfest

#33 Add workflows for all tool actions
  .github/workflows/_setup-and-cache.yml
  .github/workflows/daily-run.yml
  .github/workflows/fetch-all-articles.yml
  .github/workflows/fetch-article.yml
  .github/workflows/pr-actions.yml
  package.json
Labels: enhancement, hacktoberfest

#34 Feature/workflows 2
  .github/workflows/_setup-and-cache.yml
  .github/workflows/daily-run.yml
  .github/workflows/fetch-all-articles.yml
  .github/workflows/fetch-article.yml
  .github/workflows/pr-actions.yml
  .github/workflows/setup-and-cache/action.yml
Labels: bug, hacktoberfest

#44 Add env for switching gpt models
  .env.example
  src/utils/chat-gpt.ts
Labels: enhancement, hacktoberfest

#45 feat: add DS_Store to .gitignore
  .gitignore
Labels: enhancement, good first issue, hacktoberfest

#50 Update README.md
  docs/README.md
Labels: documentation, good first issue, hacktoberfest
